spring:
  datasource:
    url: jdbc:h2:mem:whynago;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

jwt:
  secret: iC8y1JF5aJgEHAgzniJCEW4f4OJGOZnYotlGkt0uvlw
  access:
    expiration: 1800000       # 30분 (ms)
  refresh:
    expiration: 604800000     # 7일 (ms)