spring:
  config:
    import:
      - classpath:config/application-db-local.yml
      - classpath:config/application-ai-local.yml
      - classpath:config/application-email-local.yml

jwt:
  secret: ${JWT_SECRET:"local-dev-secret-not-a-real-secret-0123456789}
  access:
    expiration: 180000000
  refresh:
    expiration: 604800000
