spring:
  application:
    name: whynago

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/whynago}
    username: ${DB_USER:user}
    password: ${DB_PASS:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

logging:
  file:
    name: logs/app.log
