-- 태그 사전 시드. 원본은 docs/TAG.md이며 이 파일은 그 사전을 tag 테이블로 옮긴 것이다.
-- question_tag가 tag_id를 참조하므로 다른 시드보다 반드시 먼저 로드해야 한다.
-- 사전 확장·수정은 docs/TAG.md를 고친 뒤 이 파일을 다시 생성한다(런타임에 태그를 새로 만드는 경로는 없다).

-- DB (31개)
INSERT INTO tag (name, category) VALUES
('인덱스', 'DB'),
('락', 'DB'),
('복합 인덱스', 'DB'),
('낙관적 락과 비관적 락', 'DB'),
('커버링 인덱스', 'DB'),
('트랜잭션 데드락', 'DB'),
('클러스터드 인덱스', 'DB'),
('정규화', 'DB'),
('실행 계획', 'DB'),
('반정규화', 'DB'),
('SQL 기본 문법', 'DB'),
('키와 제약조건', 'DB'),
('집계와 GROUP BY', 'DB'),
('N+1 문제', 'DB'),
('서브쿼리', 'DB'),
('ORM과 영속성 컨텍스트', 'DB'),
('조인', 'DB'),
('커넥션 풀', 'DB'),
('트랜잭션', 'DB'),
('파티셔닝', 'DB'),
('ACID', 'DB'),
('복제와 샤딩', 'DB'),
('격리 수준', 'DB'),
('RDB와 NoSQL', 'DB'),
('동시성 이상 현상', 'DB'),
('뷰', 'DB'),
('페이지네이션', 'DB'),
('슬로우 쿼리', 'DB'),
('NULL 처리', 'DB'),
('MVCC', 'DB'),
('트랜잭션 전파', 'DB');

-- NETWORK (30개)
INSERT INTO tag (name, category) VALUES
('OSI 7계층', 'NETWORK'),
('HTTP 캐시', 'NETWORK'),
('TCP', 'NETWORK'),
('HTTPS와 TLS', 'NETWORK'),
('UDP', 'NETWORK'),
('대칭키와 비대칭키', 'NETWORK'),
('3-way handshake', 'NETWORK'),
('쿠키와 세션', 'NETWORK'),
('흐름 제어', 'NETWORK'),
('토큰 인증', 'NETWORK'),
('혼잡 제어', 'NETWORK'),
('CORS', 'NETWORK'),
('IP와 라우팅', 'NETWORK'),
('REST API', 'NETWORK'),
('포트와 IP 주소', 'NETWORK'),
('웹소켓', 'NETWORK'),
('프록시와 리버스 프록시', 'NETWORK'),
('DNS', 'NETWORK'),
('로드 밸런싱', 'NETWORK'),
('HTTP 메서드', 'NETWORK'),
('CDN', 'NETWORK'),
('HTTP 상태 코드', 'NETWORK'),
('URL 요청 처리 흐름', 'NETWORK'),
('HTTP 버전', 'NETWORK'),
('IPv4와 IPv6', 'NETWORK'),
('서브넷과 CIDR', 'NETWORK'),
('NAT', 'NETWORK'),
('MAC 주소', 'NETWORK'),
('4-way handshake', 'NETWORK'),
('Keep-Alive', 'NETWORK');

-- ALGORITHM (26개)
INSERT INTO tag (name, category) VALUES
('시간 복잡도', 'ALGORITHM'),
('누적 합', 'ALGORITHM'),
('공간 복잡도', 'ALGORITHM'),
('DFS', 'ALGORITHM'),
('BFS', 'ALGORITHM'),
('재귀', 'ALGORITHM'),
('최단 경로', 'ALGORITHM'),
('완전 탐색', 'ALGORITHM'),
('최소 신장 트리', 'ALGORITHM'),
('백트래킹', 'ALGORITHM'),
('위상 정렬', 'ALGORITHM'),
('분할 정복', 'ALGORITHM'),
('동적 프로그래밍', 'ALGORITHM'),
('정렬 알고리즘', 'ALGORITHM'),
('정렬 안정성', 'ALGORITHM'),
('그리디', 'ALGORITHM'),
('이진 탐색', 'ALGORITHM'),
('문자열 알고리즘', 'ALGORITHM'),
('해싱', 'ALGORITHM'),
('투 포인터', 'ALGORITHM'),
('수학 알고리즘', 'ALGORITHM'),
('슬라이딩 윈도우', 'ALGORITHM'),
('계수 정렬', 'ALGORITHM'),
('힙 정렬', 'ALGORITHM'),
('조합과 순열', 'ALGORITHM'),
('시뮬레이션', 'ALGORITHM');

-- DATA_STRUCTURE (25개)
INSERT INTO tag (name, category) VALUES
('배열', 'DATA_STRUCTURE'),
('이진 탐색 트리', 'DATA_STRUCTURE'),
('동적 배열', 'DATA_STRUCTURE'),
('균형 이진 트리', 'DATA_STRUCTURE'),
('연결 리스트', 'DATA_STRUCTURE'),
('레드-블랙 트리', 'DATA_STRUCTURE'),
('이중 연결 리스트', 'DATA_STRUCTURE'),
('스택', 'DATA_STRUCTURE'),
('B+트리', 'DATA_STRUCTURE'),
('큐', 'DATA_STRUCTURE'),
('힙', 'DATA_STRUCTURE'),
('덱', 'DATA_STRUCTURE'),
('우선순위 큐', 'DATA_STRUCTURE'),
('원형 큐', 'DATA_STRUCTURE'),
('트라이', 'DATA_STRUCTURE'),
('해시 테이블', 'DATA_STRUCTURE'),
('그래프 표현', 'DATA_STRUCTURE'),
('해시 충돌', 'DATA_STRUCTURE'),
('유니온 파인드', 'DATA_STRUCTURE'),
('셋과 맵', 'DATA_STRUCTURE'),
('LRU 캐시', 'DATA_STRUCTURE'),
('트리', 'DATA_STRUCTURE'),
('트리 순회', 'DATA_STRUCTURE'),
('완전 이진 트리', 'DATA_STRUCTURE'),
('스택 오버플로와 재귀 깊이', 'DATA_STRUCTURE');

-- OS (29개)
INSERT INTO tag (name, category) VALUES
('프로세스', 'OS'),
('사용자 모드와 커널 모드', 'OS'),
('스레드', 'OS'),
('시스템 콜', 'OS'),
('PCB', 'OS'),
('인터럽트', 'OS'),
('멀티프로세스와 멀티스레드', 'OS'),
('컨텍스트 스위칭', 'OS'),
('가상 메모리', 'OS'),
('IPC', 'OS'),
('페이징', 'OS'),
('CPU 스케줄링', 'OS'),
('세그멘테이션', 'OS'),
('임계 구역', 'OS'),
('페이지 교체 알고리즘', 'OS'),
('뮤텍스와 세마포어', 'OS'),
('스와핑', 'OS'),
('경쟁 상태', 'OS'),
('캐시와 지역성', 'OS'),
('데드락', 'OS'),
('파일 시스템', 'OS'),
('동기와 비동기', 'OS'),
('좀비 프로세스', 'OS'),
('블로킹과 논블로킹', 'OS'),
('스레드 풀', 'OS'),
('선점형과 비선점형', 'OS'),
('스핀락', 'OS'),
('페이지 폴트', 'OS'),
('내부 단편화와 외부 단편화', 'OS');

-- DESIGN_PATTERN (22개)
INSERT INTO tag (name, category) VALUES
('SOLID', 'DESIGN_PATTERN'),
('데코레이터', 'DESIGN_PATTERN'),
('결합도와 응집도', 'DESIGN_PATTERN'),
('퍼사드', 'DESIGN_PATTERN'),
('상속과 합성', 'DESIGN_PATTERN'),
('프록시', 'DESIGN_PATTERN'),
('의존성 주입과 IoC', 'DESIGN_PATTERN'),
('전략', 'DESIGN_PATTERN'),
('옵저버', 'DESIGN_PATTERN'),
('싱글톤', 'DESIGN_PATTERN'),
('템플릿 메서드', 'DESIGN_PATTERN'),
('팩토리 메서드', 'DESIGN_PATTERN'),
('추상 팩토리', 'DESIGN_PATTERN'),
('빌더', 'DESIGN_PATTERN'),
('이터레이터', 'DESIGN_PATTERN'),
('어댑터', 'DESIGN_PATTERN'),
('MVC', 'DESIGN_PATTERN'),
('컴포지트', 'DESIGN_PATTERN'),
('GoF', 'DESIGN_PATTERN'),
('디미터 법칙', 'DESIGN_PATTERN'),
('DTO와 VO', 'DESIGN_PATTERN'),
('불변성과 부작용', 'DESIGN_PATTERN');

-- LANGUAGE (35개)
INSERT INTO tag (name, category) VALUES
('객체지향 4대 특성', 'LANGUAGE'),
('제네릭', 'LANGUAGE'),
('인터페이스와 추상 클래스', 'LANGUAGE'),
('컬렉션 프레임워크', 'LANGUAGE'),
('접근 제어자', 'LANGUAGE'),
('람다와 스트림', 'LANGUAGE'),
('static과 final', 'LANGUAGE'),
('Optional', 'LANGUAGE'),
('오버로딩과 오버라이딩', 'LANGUAGE'),
('예외 처리', 'LANGUAGE'),
('직렬화', 'LANGUAGE'),
('열거형', 'LANGUAGE'),
('동시성 제어', 'LANGUAGE'),
('어노테이션', 'LANGUAGE'),
('JVM 구조', 'LANGUAGE'),
('원시 타입과 래퍼', 'LANGUAGE'),
('클래스 로더', 'LANGUAGE'),
('오토박싱', 'LANGUAGE'),
('JIT 컴파일러', 'LANGUAGE'),
('문자열과 String Pool', 'LANGUAGE'),
('가비지 컬렉션', 'LANGUAGE'),
('불변 객체', 'LANGUAGE'),
('메모리 영역', 'LANGUAGE'),
('equals와 hashCode', 'LANGUAGE'),
('리플렉션', 'LANGUAGE'),
('동적 프록시', 'LANGUAGE'),
('함수형 인터페이스', 'LANGUAGE'),
('레코드', 'LANGUAGE'),
('try-with-resources', 'LANGUAGE'),
('얕은 복사와 깊은 복사', 'LANGUAGE'),
('StringBuilder와 StringBuffer', 'LANGUAGE'),
('클래스 초기화 순서', 'LANGUAGE'),
('스레드 안전성', 'LANGUAGE'),
('volatile과 원자성', 'LANGUAGE'),
('자바 버전 특징', 'LANGUAGE');

-- GENERAL_CS (40개)
INSERT INTO tag (name, category) VALUES
('OAuth 2.0', 'GENERAL_CS'),
('OIDC', 'GENERAL_CS'),
('JWT', 'GENERAL_CS'),
('인증과 인가', 'GENERAL_CS'),
('비밀번호 저장과 해싱', 'GENERAL_CS'),
('SQL 인젝션', 'GENERAL_CS'),
('XSS와 CSRF', 'GENERAL_CS'),
('접근 제어와 권한 모델', 'GENERAL_CS'),
('레이어드 아키텍처', 'GENERAL_CS'),
('헥사고날 아키텍처', 'GENERAL_CS'),
('모놀리식과 마이크로서비스', 'GENERAL_CS'),
('API 게이트웨이', 'GENERAL_CS'),
('서비스 디스커버리', 'GENERAL_CS'),
('메시지 큐', 'GENERAL_CS'),
('이벤트 드리븐 아키텍처', 'GENERAL_CS'),
('분산 트랜잭션과 사가', 'GENERAL_CS'),
('멱등성', 'GENERAL_CS'),
('캐시 전략', 'GENERAL_CS'),
('분산 캐시', 'GENERAL_CS'),
('확장성과 스케일 아웃', 'GENERAL_CS'),
('고가용성과 장애 대응', 'GENERAL_CS'),
('부하 테스트와 성능 측정', 'GENERAL_CS'),
('세션 클러스터링', 'GENERAL_CS'),
('무중단 배포', 'GENERAL_CS'),
('CI/CD', 'GENERAL_CS'),
('컨테이너와 도커', 'GENERAL_CS'),
('컨테이너 오케스트레이션', 'GENERAL_CS'),
('분산 추적', 'GENERAL_CS'),
('환경 설정과 시크릿 관리', 'GENERAL_CS'),
('API 버저닝', 'GENERAL_CS'),
('에러 처리와 응답 규격', 'GENERAL_CS'),
('단위 테스트와 통합 테스트', 'GENERAL_CS'),
('TDD', 'GENERAL_CS'),
('Git과 브랜치 전략', 'GENERAL_CS'),
('시맨틱 버저닝', 'GENERAL_CS'),
('문자 인코딩', 'GENERAL_CS'),
('시간대와 날짜 처리', 'GENERAL_CS'),
('정규 표현식', 'GENERAL_CS'),
('컴파일러와 인터프리터', 'GENERAL_CS'),
('진법과 비트 표현', 'GENERAL_CS');
